In [12]:
import numpy as np

In [13]:
arr=[[1.,0.,0.],
    [0.,2.,1.]]

In [14]:
# We have created an array using the array method of np. np.array(the_required_item)
a=np.array(arr)

In [15]:
#determines the axis
a.ndim

2

In [16]:
b=np.array(arr,dtype=complex)

In [17]:
b

array([[1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 2.+0.j, 1.+0.j]])

In [18]:
#When using a method which creates an array, always use double parentheses.
np.ones((2,3,4)) #There is another method called as zero and zeros_like. zeros_like convert array into zero

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [19]:
np.ones((2,1,1))

array([[[1.]],

       [[1.]]])

In [20]:
# Three brackets to be noticed.
arr2=[[[1.],
     [1.]]]

In [21]:
np.array(arr2)

array([[[1.],
        [1.]]])

In [22]:
np.arange( 0, 2, 0.3 )                 # it accepts float arguments

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [23]:
# If we want number of elements instead of giving number of steps skipped, we use linspace
np.linspace(2,10,3)

array([ 2.,  6., 10.])

In [24]:
t=np.random.rand